name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Dependances
        run: |
          docker run --rm -v "$PWD:/src" aquasec/trivy:0.69.3 fs \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            /src/requirements.txt
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Test Dockerfile
        run: |
          echo "ecrire ici le scrypt de contrôle du Dockerfile"
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
